
name: stac_ipyleaflet
channels:
    - conda-forge
dependencies:
    - jupyterlab
    - pip
    - pip:
        - ipyleaflet==0.17.2
        - ipywidgets==8.0.4
        - ipyevents
        - matplotlib
        - pydantic
        - shapely
        - requests
        - rio_tiler
        - rioxarray
        - xarray
        - pystac_client==0.6.1
